### PR TITLE
Allow clients supply a document where to process fragments in

### PR DESCRIPTION
**Pull request by Stvad**
Use-case: processing and extracting text fragments for a document downloaded in the background (and potentially not in the browser in the future).  
I'm using this to enable the following extension: https://github.com/transclude-me/extension

### CODE REVIEW

**Comment by Stvad** [comment]
thanks for taking a look @tfmar, updated the PR!

**Review by tfmar — APPROVED** [review]

**Comment by Stvad** [comment]
@tfmar can I bother you to do an NPM release? 🙂

**Comment by tomayac** [comment]
Done, `v5.3.0` just went out.

**Comment by Stvad** [comment]
Thank you!

**Pull request merged**
