### PR TITLE
Restoring compiled version

### PR DESCRIPTION
**Pull request by tfmar**
This restores the compiled version of the polyfill in the `dist/` directory, allowing for importers to use the compiled version. It also removes `dist/` from the `.gitignore` file so that this version will be up-to-date.

### CODE REVIEW

**Comment by tomayac** [comment]
We should not do this, it’s totally possible for importers to use the compiled version thanks to  https://github.com/GoogleChromeLabs/text-fragments-polyfill/blob/806feed7da2b0cd789fb423339e49a8b6b38c0ce/package.json#L11.

**Comment by tomayac** [comment]
Also see https://github.com/GoogleChromeLabs/text-fragments-polyfill/pull/2#discussion_r463253819.

**Comment by tfmar** [comment]
Hmm, something's still not right; the version that shows up on unpkg is outdated. What's the mechanism that provides a compiled version if we aren't uploading one ourselves?

**Comment by JesusDeLaProg** [comment]
> We should not do this, it’s totally possible for importers to use the compiled version thanks to
> 
> https://github.com/GoogleChromeLabs/text-fragments-polyfill/blob/806feed7da2b0cd789fb423339e49a8b6b38c0ce/package.json#L11

I have seen in the NPM documentation that files and directories included in the `files` array should not be excluded by .gitignore, so I think we need to keep this file up to date with src at all time.
https://docs.npmjs.com/files/package.json#files:~:text=Files%20included%20with%20the%20%E2%80%9Cpackage.json%23files%E2%80%9D%20field,be%20excluded%20through%20.npmignore%20or%20.gitignore.

**Comment by tomayac** [comment]
A new version gets deployed (to npm, but as a side effect also unpkg.com) when we run `npm publish`. To build, run `npm prepare` (this script always runs when you run the publish script, and also after someone install the package from npm).

**Comment by tomayac** [comment]
(Since I’m currently the sole package owner, I think I need to run the publish script.)

**Comment by tomayac** [comment]
Ping me your npm accounts and I will add you tomorrow: https://docs.npmjs.com/creating-a-new-npm-user-account.

**Pull request closed without merging**
