### PR TITLE
Adding method to generate the fragment from a Range

### PR DESCRIPTION
**Pull request by erickjth**

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks a lot for the PR! Before it can be merged, could you make the CLA bot happy, please?

**Comment by tomayac** [comment]
Any update on the CLA, @erickjth?

**Comment by erickjth** [comment]
> Any update on the CLA, @erickjth?

@tomayac I was thinking that was done, it see the checkmark, but no for the CI/ build, I am not sure what is missing actually.

**Review by tomayac — APPROVED** [review]
LGTM, approval. Thank you!

**Comment by tomayac** [comment]
Thanks again, released as `v5.7.0`.

**Pull request merged**
