### PR TITLE
Allow to import `text-fragment-utils` as ES molude from Node.js

### PR DESCRIPTION
**Pull request by ttanimichi**
Hi, I'm looking for an open-source parser of Text Fragments for Node.js. Can you export `text-fragment-utils` and set `"type": "module"` in the package.json to be able to import it from Node.js?

```js
// main.mjs

import {
    getFragmentDirectives,
    parseFragmentDirectives,
} from "text-fragments-polyfill/text-fragment-utils"

const h = "#:~:text=examples%20in%20documents.-,You%20may%20use%20this,-domain%20in%20literature"
const fragmentDirectives = getFragmentDirectives(h);
const parsedFragmentDirectives = parseFragmentDirectives(fragmentDirectives);

console.log(parsedFragmentDirectives);
```

result:

```
$ node main.mjs 
{
  text: [
    {
      prefix: 'examples in documents.',
      textStart: 'You may use this',
      textEnd: '',
      suffix: 'domain in literature'
    }
  ]
}
```

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, approval

Thank you! The only thing missing is that you sign the contribution agreement, see this [message](https://github.com/GoogleChromeLabs/text-fragments-polyfill/pull/98/checks?check_run_id=4331831017) for details.

**Comment by ttanimichi** [comment]
Signed. Can you re-run the job to rescan?

**Comment by ttanimichi** [comment]
I'v force-pushed the commit to re-run the job. CLA was successful.

**Comment by tomayac** [comment]
Looks like this makes the test suite unhapp:

```
> ./node_modules/karma/bin/karma start --single-run

npm ERR! Test failed.  See above for more details.
26 11 2021 09:05:11.340:ERROR [config]: Error in config file!
  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/text-fragments-polyfill/text-fragments-polyfill/karma.conf.js
require() of ES modules is not supported.
require() of /home/runner/work/text-fragments-polyfill/text-fragments-polyfill/karma.conf.js from /home/runner/work/text-fragments-polyfill/text-fragments-polyfill/node_modules/karma/lib/config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename karma.conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/text-fragments-polyfill/text-fragments-polyfill/package.json.
```

**Pull request merged**
